#!/bin/bash    

#HOST="your.ftp.host.dom"
#USER="username"
#PASS="password"
#URL="$USER:$PASS@$HOST"
#LCD="/path/of/your/local/dir"
#RCD="/path/of/your/remote/dir"

URL=$1
RCD=$2
LCD=$3
shift 3

set +x

lftp -c "set ftp:list-options -a;
open ftp://$URL; 
cd $RCD;
lcd $LCD;
mirror --parallel=10 --use-cache --verbose --allow-chown --allow-suid --no-umask $@
"
