#!/bin/bash -x

systemctl restart systemd-journald
systemctl restart cronie
systemctl restart user-0

systemctl stop asd
sync
echo 3 > /proc/sys/vm/drop_caches
systemctl start asd

systemctl restart media-downloader-bot
