#!/bin/bash -x

systemctl restart systemd-journald
systemctl restart cronie
systemctl restart polkit
systemctl restart user-0.slice

systemctl stop asd
sync
echo 3 > /proc/sys/vm/drop_caches
systemctl start asd

systemctl restart media-downloader
