#!/bin/sh
## The default configuration incase you want to revert
#       P0 - Enabled - FID = 88 - DID = 8 - VID = 20 - Ratio = 34.00 - vCore = 1.35000
#       P1 - Enabled - FID = 78 - DID = 8 - VID = 2C - Ratio = 30.00 - vCore = 1.27500
#       P2 - Enabled - FID = 84 - DID = C - VID = 68 - Ratio = 22.00 - vCore = 0.90000

modprobe msr cpuid

## P0 = 3.800GHz, 1.3500v
zenstates -p 0 -f 98 -d 8 -v 20

## P1 = 3.800GHz, 1.3500v
zenstates -p 1 -f 98 -d 8 -v 20

## P2 = 2.200GHz, 0.9000v
zenstates -p 2 -f 84 -d C -v 68

## List the result.
zenstates -l
