#!/bin/bash

# based on http://wiki.webmproject.org/ffmpeg/vp9-encoding-guide

SOURCE=$1
WEBM="${SOURCE%.*}".webm

THREADS=6

SIZE=${2:-240}
QUALITY=${3:-35} # 0-63, lower is better quality
AUDIO_OPTIONS="-c:a libopus -b:a 64k"
FILTERS="scale=-1:$SIZE"

#SUBTITLES="Cowspiracy_brp.srt"
#FILTERS+=", subtitles=$SUBTITLES"

nice ffmpeg -i "$SOURCE" -c:v libvpx-vp9 -f webm $AUDIO_OPTIONS \
  -threads $THREADS -speed 4 -tile-columns $THREADS -frame-parallel 1 \
  -vf "$FILTERS" -crf $QUALITY -b:v 0 \
  "$WEBM" \
\
&& rm "$SOURCE"

# two pass options
#  -pass 1 -an /dev/null \
#  -pass 2 -auto-alt-ref 1 -lag-in-frames 25 \
